clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  test_pull_request:
    image: docker
    commands:
      - docker build -t squidex/squidex-identity:test_pull_request .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    when:
      event: pull_request

  build_dev:
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t squidex/squidex-identity:dev .
      - docker push squidex/squidex-identity:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: [ master ]

  build_release:
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t squidex/squidex-identity:latest -t squidex/squidex-identity:$TAG .
      - docker push squidex/squidex-identity:latest
      - docker push squidex/squidex-identity:$TAG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    environment:
      - TAG=${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  slack:
    image: plugins/slack
    template: >
      {{#success build.status}}
        Squidex Identity build {{build.number}} succeeded. Good job.
      {{else}}
        Squidex Identity build {{build.number}} failed. Fix me please.
      {{/success}}
    secrets: [ slack_webhook ]
    when:
      status: [ failure, success ]

  cleanup:
    image: docker
    commands:
      - docker system prune -f
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    when:
      status: failure